src/APP.Platform/Pages/Sobre/Index.cshtml
=> remove clickbait word

src/APP.Platform/Pages/Shared/_Layout.cshtml, src/APP.Platform/Pages/Sobre/Index.cshtml, src/APP.Platform/wwwroot/css/aboutStyle.css, src/APP.Platform/wwwroot/css/codewithme.general.css
Ajuste da lógica do about para ser conforme todas as outras
=> Padding do sobre corrigido

src/APP.Platform/Pages/Shared/_Layout.cshtml, src/APP.Platform/wwwroot/css/codewithme.general.css
- Basicamente a lógica de renderização condicional em javascript foi passada para media query
=> Trocado a lógica javascript para media query

src/APP.Platform/wwwroot/js/afterLoadHome.js
=> corrige lógica para seleção inicial da tabs home

src/Core/Domain/Interfaces/WebServices/IJoinTimeWebService.cs, src/Core/Domain/Interfaces/WebServices/ITimeSelectionWebService.cs, src/Core/Infrastructure/DependencyInjection.cs, src/Core/Infrastructure/WebServices/Core/JointTimeWebService.cs, src/Core/Infrastructure/WebServices/Core/TimeSelectionWebService.cs, src/Core/Presentation/Workers/JoinTimeWorker.cs, src/Core/Presentation/Workers/LiveCloseWorker.cs, src/Core/Presentation/Workers/LiveNotifyWorker.cs, src/Core/Presentation/Workers/TimeSelectionWorker.cs, tests/JoinTime/JoinTimeWorkerTests.cs, tests/TimeSelection/TimeSelectionWorkerTests.cs
=> Cria os webServices para os Workers

src/APP.Platform/Pages/Index.cshtml, src/APP.Platform/Pages/Shared/_Layout.cshtml, src/APP.Platform/wwwroot/js/afterLoadHome.js
=> Correção de erros no console quando usuário deslogado.

src/Core/Presentation/Workers/JoinTimeWorker.cs, src/Core/Presentation/Workers/LiveCloseWorker.cs, src/Core/Presentation/Workers/LiveNotifyWorker.cs, src/Core/Presentation/Workers/TimeSelectionWorker.cs, tests/JoinTime/JoinTimeWorkerTests.cs, tests/TimeSelection/TimeSelectionWorkerTests.cs
=> fix test scoped services

src/APP.Platform/Pages/Perfil/Index.cshtml.cs
Perfil e Notification alerts were ignored
=> null check added for _perfil + deleted SaveFoto()

src/APP.Platform/Pages/Components/ScheduleActions/_VerAjudasDisponiveis.cshtml, src/APP.Platform/Pages/Shared/_Layout.cshtml, src/APP.Platform/wwwroot/js/afterLoadHome.js
=> ajusta erro ao renderizar calendario na home

src/APP.Platform/Pages/Canal/Index.cshtml, src/APP.Platform/wwwroot/css/codewithme.general.css
- Substitui o estilo inline da tag div pelas classes do bootstrap
- Diminui o gap entre a imagem de perfil e os títulos do canal do usuário 
- Adicionei um espaçamento no topo dos títulos para ficar o mais parecido possível com o designer e sem alterar tamanhos, cores ou fonte
- Removi os as propriedades de estilos desnecessárias
=> update titles of user channel

src/APP.Platform/Models/ConcluidosCardPageModel.cs, src/APP.Platform/Models/ConsideracoesPendentesCardPageModel.cs, src/APP.Platform/Models/EventosMarcadosCardPageModel.cs, src/APP.Platform/Models/EventosProximosCardPageModel.cs, src/APP.Platform/Pages/Components/ModalJoinTime/_ModalJoinTimePanel.cshtml, src/APP.Platform/Pages/Components/TimeSelections/_ConcluidosCard.cshtml, src/APP.Platform/Pages/Components/TimeSelections/_ConsideracoesPendentesCard.cshtml, src/APP.Platform/Pages/Components/TimeSelections/_EventosMarcadosCard.cshtml, src/APP.Platform/Pages/Components/TimeSelections/_EventosProximosCard.cshtml, src/APP.Platform/Pages/Components/TimeSelections/_ModalFreeTimePanel.cshtml
Propagando UserName nos card da agenda, permitindo o redirecionamento para o canal de forma correta.
=> Alteração avatar redirect canal

src/APP.Platform/Pages/Studio/Index.cshtml.cs
Fiz uma refatoração do código para usar o construtor primário.
=>  Refatoração do código para usar o construtor primário.

.github/workflows/CI-CD.yml
NO CI/CD estavamos usando o comando docker compose com `-`, na pratica isso significa que estavamos usando uma versão menos atual do comando
=> update for docker compose v2

src/Core/Domain/Interfaces/WebServices/IChatWebService.cs, src/Core/Domain/Interfaces/WebServices/ICommentWebService.cs, src/Core/Infrastructure/DependencyInjection.cs, src/Core/Infrastructure/WebServices/Core/ChatWebService.cs, src/Core/Infrastructure/WebServices/Core/CommentWebService.cs, src/Core/Presentation/Queues/ChatsQueue.cs, src/Core/Presentation/Queues/CommentsQueue.cs, src/Core/Presentation/Queues/LiveThumbnailQueue.cs
=> Cria os WebServices para os Queues

src/APP.Platform/wwwroot/css/aboutStyle.css
Só arrumei o padding na pagina about para respeitar o design esperado
=> Arrumado o padding na página sobre

src/APP.Platform/Pages/Shared/_InternetConnectionQuality.cshtml, src/APP.Platform/Pages/Studio/Index.cshtml, src/APP.Platform/Pages/Studio/OBS.cshtml
Foi implementada uma função para testar a velocidade da internet utilizando uma imagem como referência. A função calcula a velocidade com base no tempo de carregamento da imagem e exibe a qualidade da conexão (Alta, Média, Baixa) no componente correspondente.
Mudanças realizadas:
- Adicionada a função `getInternetSpeed` para medir a velocidade da internet.
- Atualizado o componente `_ConnectionQuality.cshtml` para chamar a função de teste de velocidade.
- Ajustado o HTML para mostrar a qualidade da conexão.
=> feat: implementa teste de velocidade da internet

src/APP.Platform/Pages/Notificacoes/Index.cshtml.cs, src/APP.Platform/Pages/Perfil/Index.cshtml, src/APP.Platform/Pages/Perfil/Index.cshtml.cs
=> Refatoração para utilizar o construtor primário em Pages/Perfil/Index.cshtml.cs

src/APP.Platform/Pages/Notificacoes/Index.cshtml.cs, src/APP.Platform/wwwroot/js/ScheduleLiveFlowOnChannel.js, src/APP.Platform/wwwroot/js/ScheduleLiveSelectionTagVerifier.js, src/APP.Platform/wwwroot/js/ScheduleLiveSelectionTagVerifierOnChannel.js, src/APP.Platform/wwwroot/js/liveFlow.js, src/APP.Platform/wwwroot/js/scheduleLivePreviewObserverOnChannel.js, src/APP.Platform/wwwroot/js/timePickerFlow.js
Troquei todas as declarações com a keyword var pelas let/const no diretório `src/APP.Plataform/wwwroot/js`
=> Swapping 'var' for 'const'/'let'

src/APP.Platform/Pages/Notificacoes/Index.cshtml.cs, src/APP.Platform/wwwroot/css/codewithme.general.css, src/APP.Platform/wwwroot/js/renderComponentsCapacitacao.js, src/APP.Platform/wwwroot/js/renderComponentsPedirAjuda.js
Atualização completa do componente "card de sessões"
Antes:
Depois:
=> update card of sections

src/APP.Platform/Pages/Notificacoes/Index.cshtml.cs, tests/Perfil/PerfilBusinessLogicTests.cs
+ Created tests for failing scenarios.
+ Created missing tests
=> New tests for PerfilBussinessLogic

src/APP.Platform/Pages/Components/ScheduleActions/_FormsOneToOne.cshtml, src/APP.Platform/Pages/Components/ScheduleActions/_FormsRequestHelp.cshtml, src/APP.Platform/wwwroot/css/codewithme.general.css
Corrigido o modal-body adicionando uma classe de evento para os que precisam da configuração antiga
=> arrumado os outros modais

src/APP.Platform/Pages/Components/ScheduleActions/_VerAjudasDisponiveis.cshtml, src/APP.Platform/wwwroot/css/codewithme.general.css
Atualizei as cores das abas de navegação padrão, "hover" e ativo
Antes:
Depois:
=> update nav-tabs style standards

src/APP.Platform/wwwroot/js/CursosAndEventosFlow.js, src/APP.Platform/wwwroot/js/OneToOneEvent/OneToOneFlow.js, src/APP.Platform/wwwroot/js/ScheduleLiveFlowOnChannel.js
=> Remove the declaration of the unused timeSelectionIdForLive variable

src/APP.Platform/Pages/Watch/Index.cshtml.cs
=> Substitui pelo objeto ja instanciado

.husky/pre-commit, node_modules/.bin/husky, node_modules/.bin/husky.cmd, node_modules/.bin/husky.ps1, node_modules/.package-lock.json, node_modules/husky/LICENSE, node_modules/husky/README.md, node_modules/husky/bin.js, node_modules/husky/husky, node_modules/husky/index.d.ts, node_modules/husky/index.js, node_modules/husky/package.json, package-lock.json, package.json, src/APP.Platform/Pages/Watch/Index.cshtml.cs
Executa o comando "dotnet csharpier ." automático ao commitar. 
Por hora é preciso instalar o Husky - "npm i"
=> Executa o comando "dotnet csharpier ." ao commitar

src/APP.Platform/Pages/Components/ScheduleActions/_FormsOneToOne.cshtml, src/APP.Platform/Pages/Components/ScheduleActions/_FormsRequestHelp.cshtml
Só arrumei o timepicker, colocando 11 no lugar de 10
=> Trocado o 10 por 11 no lugar correto

src/Core/Infrastructure/Migrations/20240806235029_AddSchemaHelpResponse.Designer.cs, src/Core/Infrastructure/Migrations/20240806235029_AddSchemaHelpResponse.cs
Aplicando migration da entidade HelpResponse no novo ambiente develop.
=> Novo ambiente de desenvolvimento

src/Core/Infrastructure/Migrations/20240806235029_AddSchemaHelpResponse.Designer.cs, src/Core/Infrastructure/Migrations/20240806235029_AddSchemaHelpResponse.cs
=> Lf feature organizing environment

src/APP.Platform/wwwroot/js/timePickerFlow.js
Foi retirado  todo encadeamento de if/else da função  displayTotalTime
Fiz o mapeamento de todas as condições e gerei um if único para cada condição
assim ficando mais fácil a leitura do codigo
=> Refactor: diminuindo a complexidade da funcao displayTotalTime

src/APP.Platform/wwwroot/js/afterLoadHome.js
=> Setas cinzas quando não há eventos

src/APP.Platform/Pages/Components/ScheduleActions/_FormsCursosAndEventos.cshtml
=> removido o > extra

src/APP.Platform/Pages/Watch/Index.cshtml.cs, src/APP.Platform/wwwroot/js/CursosAndEventos/CursosAndEventosFlow.js, src/APP.Platform/wwwroot/js/OneToOneEvent/OneToOneFlow.js, src/APP.Platform/wwwroot/js/RequestHelpEvent/RequestHelpFlow.js, src/APP.Platform/wwwroot/js/ScheduleLiveFlow.js, src/Core/Infrastructure/Repositories/CommentRepository.cs, src/Core/Presentation/EndPoints/CommentEndPoints.cs, src/Core/Presentation/EndPoints/PerfilsEndPoints.cs, tests/Comment/CommentBusinessLogicTests.cs, tests/Comment/CommentEndpointsTests.cs, tests/HelpResponse/HelpResponseRepositoryTest.cs, tests/Perfil/PerfilEndPointsTests.cs
=> Remove the unused declaration FirstForm

src/APP.Platform/wwwroot/js/CursosAndEventos/CursosAndEventosFlow.js, src/APP.Platform/wwwroot/js/CursosAndEventos/ValidacaoCursosAndEventos.js, src/APP.Platform/wwwroot/js/OneToOneEvent/OneToOneFlow.js, src/APP.Platform/wwwroot/js/OneToOneEvent/ValidacaoOneToOne.js, src/APP.Platform/wwwroot/js/RequestHelpEvent/RequestHelpFlow.js, src/APP.Platform/wwwroot/js/RequestHelpEvent/ValidacaoRequestHelp.js
Adicionado validação para eventos que compartilham o mesmo horário e os inputs iniciam na data atual, com soma de 1 hora
=> Validacao de eventos no mesmo horário e inputs com tempo atual

src/APP.Platform/Pages/Components/ModalJoinTime/_ModalJoinTimeForRequestHelp.cshtml, src/APP.Platform/wwwroot/css/codewithme.general.css, src/APP.Platform/wwwroot/js/renderComponentsCapacitacao.js, src/APP.Platform/wwwroot/js/renderComponentsPedirAjuda.js
Modais de detalhes dos eventos (de qualquer tipo) reestilizados
=> Modais de detalhes dos eventos re-estilizados

node_modules/.package-lock.json, package-lock.json, src/APP.Platform/Pages/Canal/Index.cshtml, src/APP.Platform/Pages/Canal/Index.cshtml.cs
Feita alteração na posição da função nextVideos e check box para scroll infinito funcionar em todos os canais.
=> LM hotfix scroll infinito aplicado nos videos após acessar outros canais

tests/FreeTime/FreeTimeBackstageTest.cs
Criacao de teste para o metodo create da entidade FreeTimeBackstage
=> Teste para metodo Create da entidade FreeTimeBackstage

src/APP.Platform/Pages/Components/ScheduleActions/_VerAjudasDisponiveis.cshtml, src/APP.Platform/Pages/Index.cshtml, src/APP.Platform/wwwroot/css/codewithme.general.css
=> novos botoes

src/APP.Platform/Pages/Components/_Agenda.cshtml, src/APP.Platform/wwwroot/css/codewithme.general.css
Atualizado o layout das tabs de paginação da agenda
Antes:
Com as alterações:
=> update layout of nav tabs in agenda modal

src/APP.Platform/Pages/Canal/Index.cshtml
=> Substituir mãos por setas

src/Core/Infrastructure/WebServices/Core/JointTimeWebService.cs, src/Core/Presentation/EndPoints/JoinTimeEndPoints.cs
=> Hotfix no endpoint jointime. Foi alterado URL montada no webservice
